In [4]:
import numpy as np

arr2d = np.arange(36).reshape(9,4)

In [5]:
arr2d


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [33]:
arr2d[6,3]

27

In [37]:
arr2d[:,::2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22],
       [24, 26],
       [28, 30],
       [32, 34]])

In [8]:
arr2d[:,[0,3,2,1]]
#fancy indexing

array([[ 0,  3,  2,  1],
       [ 4,  7,  6,  5],
       [ 8, 11, 10,  9],
       [12, 15, 14, 13],
       [16, 19, 18, 17],
       [20, 23, 22, 21],
       [24, 27, 26, 25],
       [28, 31, 30, 29],
       [32, 35, 34, 33]])

In [38]:
arr3d = np.arange(64).reshape(4,4,4)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [47]:
arr3d[2,0,1]
#jo uper command likha hai aur jo neeche command likha hai woh dono same hain 
#arr3d[2][0][1]
#ye wala index [2] item number ko batanay ke liye hai like 32-47 wala 4x4 matrix
#ye wala index [0] row number batanay ke liye hai like 32-47 walay matrix ki 1st row jo 0th index pe hoti hai
#ye wala index [1] column number batanay ke liye hai like 32-47 walay matrix ki 2nd column jo 1st index pe hoti hai 

33

In [48]:
https://www.youtube.com/watch?v=PbKOrSottRQ1&t=56s&pp=ygUfc2xpY2luZyBpbiBweXRob24gMmQgbnVteSBhcnJheQ%3D%3D

SyntaxError: invalid decimal literal (4281016075.py, line 1)

In [50]:
arr3d[3:4,1:3,1:3]

array([[[53, 54],
        [57, 58]]])

In [51]:
arr3d[1:3,1:3,1:3]

array([[[21, 22],
        [25, 26]],

       [[37, 38],
        [41, 42]]])

In [57]:
a=np.arange(1,10,+2)

In [58]:
print(a)


[1 3 5 7 9]


In [ ]:
You're right! Let's clarify the extraction for arr3d[1:3, 1:3, 1:3] using the correct details.

First dimension 1:3: This selects the 2nd and 3rd slices (indices 1 and 2).

Second dimension 1:3: This selects rows 1 and 2 from those slices.

Third dimension 1:3: This selects columns 1 and 2 from those rows.

So, breaking it down step by step:

For Slice arr3d[1] (2nd Slice):
lua
Copy code
[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
Selecting rows 1 and 2 gives:
lua
Copy code
[[20 21 22 23]
 [24 25 26 27]]
Selecting columns 1 and 2 from those rows gives:
lua
Copy code
[[21 22]
 [25 26]]
For Slice arr3d[2] (3rd Slice):
lua
Copy code
[[32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]]
Selecting rows 1 and 2 gives:
lua
Copy code
[[36 37 38 39]
 [40 41 42 43]]
Selecting columns 1 and 2 from those rows gives:
lua
Copy code
[[37 38]
 [41 42]]
Final Result
Combining these results, the output for arr3d[1:3, 1:3, 1:3] will be:

lua
Copy code
[[[21 22]
  [25 26]]

 [[37 38]
  [41 42]]]