In [9]:
import numpy as np


In [11]:
list1 = [1,2,3,4,5]
print ("Before converting list into numpy array.")

print(type(list1))
arr1 = np.array(list1)

print ("After converting list into numpy array.")
type(arr1)

Before converting list into numpy array.
<class 'list'>
After converting list into numpy array.


numpy.ndarray

In [23]:
#in lists we can not do this type of operation, we will need to access indexes separately with a loop. In numpy arrays we can do both.
arr1*2

array([ 2,  4,  6,  8, 10])

In [21]:
print(arr1 > 2)

[False False  True  True  True]


In [33]:
list2d = [[1,2], [3,4]]
arr2d = np.array(list2d)

In [37]:
print(arr2d)

[[1 2]
 [3 4]]


In [39]:
array2d = np.arange(4).reshape(2,2)

In [55]:
for i in range(2):
    for j in range(2):
        input(array2d[i][j])

for i in range(2):
    for j in range(2):
        print(array2d[i][j])
        print("\t")
    print ("\n")


0 1
1 2
2 3
3 4


0
	
1
	


2
	
3
	




In [97]:
for i in range(2):
    for j in range(2):
        print ("*")
    print ("\n")
    
    

*
*


*
*




In [105]:
array2_2d = np.arange(36).reshape(4,9)
array2_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [137]:
array2_2d[::2,2:4]

array([[ 2,  3],
       [20, 21]])

In [139]:
array2_2d[:2,2:4]

array([[ 2,  3],
       [11, 12]])